version: '3.8'
services:
  api:
    container_name: repoinsight_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - repoinsight_network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - ./dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5930
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
      MB_EMBEDDING_SECRET_KEY: repoinsight_project
    networks:
      - repoinsight_network
    expose:
      - 3000
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  metabase-db:
    image: postgres:15  
    container_name: postgres
    hostname: postgres
    ports:
      - 5930:5930
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    command: -p 5930
    
    networks:
      - repoinsight_network
    
networks:
  repoinsight_network:
    external: true